name: Meta Pipeline
on:
  push:
  pull_request:
jobs:
  meta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: python -m pip install -r tools/requirements.txt
      - name: Repo Hygiene
        run: ./tools/check_repo_hygiene.sh
      - name: Ensure DAG is committed (no diff)
        run: ./tools/check_dag_clean.sh
      - name: Verify DAG
        run: ./tools/verify_dag.py
      - name: Verify MANIFEST.sha256
        run: ./tools/verify_manifest.py
